### ISSUE TITLE
Add phantomjs to requirements

### ISSUE THREAD

**Issue by slavahatnuke** [linkshare/plus.garden#4]
need test that phantomjs installed and works correct
for ex. ubuntu requires some additional packages

looks like need to check phantomjs on ensure step

http://phantomjs.org/build.html

**Comment by volodymyrpoliakov** [comment]
phantome.js is instaling via NPM

**Comment by volodymyrpoliakov** [comment]
I think we can close this

**Comment by slavahatnuke** [comment]
I met issues with this today, could you give me time to investigate this more, because looks like with ubuntu we need to install fonts libs and other stuff. I would make some with phantomjs when we ensure services that phantomjs works correct

**Comment by volodymyrpoliakov** [comment]
yeah, fonts should be installed in system, that should be added to docs
