### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by slavahatnuke** [linkshare/plus.garden#6]
looks like need some guide to start testing in 5 steps

**Comment by volodymyrpoliakov** [comment]
isn't this enough
https://github.com/linkshare/plus.garden/blob/master/README.md

**Comment by slavahatnuke** [comment]
today decided to integrate garden to real project, and it feels like not polished tool. I know this framework and it looks simple to integrate but for end users/developers/QA-persons need some help. 

I would improve this documentation and simplify as much as possible and add the simples steps to have Twitter Health Checker workable in the first action

#1 sudo npm install --global plus.garden
#2 plus.garden init
#3 ./garden.js test 

should work as a bee :)

**Comment by volodymyrpoliakov** [comment]
I think we wiil just add another scenario with global installing

**Comment by slavahatnuke** [comment]
I plan to fix some issues after vacation and looks like I can figure out
some simple steps for this. will make outline, then would be great to
discuss this, I propose to keep this issue opened and assign to me.

2015-08-18 22:24 GMT+03:00 Vladimir Polyakov notifications@github.com:

**Comment by arrobeusa** [comment]
I agree the setup is not simple enough yet.  The biggest selling point of Garden should be ease of install.

**Comment by slavahatnuke** [comment]
Yeah, will be in office at the end of next week want to take a look on
this. It shuld fly ;)

четверг, 20 августа 2015 г. пользователь Robert Rotarius написал:
