### ISSUE TITLE
Hooks, loading fixtures does not work from the box

### ISSUE THREAD

**Issue by slavahatnuke** [linkshare/plus.garden#8]
---

//  >>> this.Garden = Garden; // this.Garden.wait required, need for hooks, need to delegate Garden.wait 
// >>> this.garden = garden; // needs for getting services in hooks

// World should contain this.Garden, this.garden

var World = function World(callback) {

  this.config = garden.get('config');

  this.Garden = Garden;
  this.garden = garden;

  this.garden.get('Webdriver.Browser').create(function (browserService) {
    this.browserService = browserService;
    this.driver = browserService.driver;
    this.browser = browserService.browser;
    this.proxy = browserService.proxy;
    callback();
  }.bind(this));

};

**Comment by volodymyrpoliakov** [comment]
it doesn't work from the box because of need to install fixture.loader module

**Comment by slavahatnuke** [comment]
with fixture loader that does not work too :)

**Comment by slavahatnuke** [comment]
I will take a looks after vacation, on this and update codebase

**Comment by slavahatnuke** [comment]
closed with commit 521946efd2b6d7432e8037e0c35d690d94d9d3d4
by Emma @emmac1016
